// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mutkkrecdimqrwccefza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11dGtrcmVjZGltcXJ3Y2NlZnphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzOTQ5MjcsImV4cCI6MjA0OTk3MDkyN30.rJUGUnbnq8ZUlwn4sxj-luasqDfrBLWwBriQm-esKAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);